version: 2

sources:
  - name: olist_dw          # "apelido"
    database: olist_dw      # nome do db
    schema: raw
    tables:
      - name: source_customers_dataset
      - name: source_geolocation_dataset
      - name: source_order_items_dataset
      - name: source_order_payments_dataset
      - name: source_order_reviews_dataset
      - name: source_orders_dataset
      - name: source_product_category_name_translation_dataset
      - name: source_products_dataset
      - name: source_sellers_dataset